### ISSUE TITLE
add examples

### ISSUE THREAD

**Issue by francogrex** [whily/yalo#5]
Please consider adding a few examples when in qemu:
Start your journey on yalo v0.0.0!
REPL>
... and then what? some demo with print-screens would be useful.

**Comment by whily** [comment]
So far the only thing REPL does is to echo what is typed, therefore no example yet. Will implement a simple interpreter after implementing the code to switch to 64 bit long mode. Please check the plan here: https://github.com/whily/yalo#status

**Comment by francogrex** [comment]
ok thanks I am looking forward. This is a top project please keep up the nice work. FG
